admin_token = 'admin123'
api_keys = []
api_token = '123'
reactivation_threshold = '10m'
server_address = ':8981'

[auto_reactivation]
cron_spec = '22 23 * * *'
enabled = true
interval = '5s'
mode = 'interval'
timezone = 'Asia/Shanghai'
